// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDjCuLHvDk0Rg4VIBYNuROkY1s3pGVb4c',
    appId: '1:192172840760:web:c93dbdcaa01fcfb9cb93cd',
    messagingSenderId: '192172840760',
    projectId: 'test-7b9c2',
    authDomain: 'test-7b9c2.firebaseapp.com',
    storageBucket: 'test-7b9c2.appspot.com',
    measurementId: 'G-C213B3W448',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-HAswYa2uYxzUiYQmQS_jRxA_fh2XVPw',
    appId: '1:192172840760:android:e70603ff04054269cb93cd',
    messagingSenderId: '192172840760',
    projectId: 'test-7b9c2',
    storageBucket: 'test-7b9c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAT06k0i_ZYYNgDY60bSXXwhgQGV6RhWc',
    appId: '1:192172840760:ios:ce8f2497993d1d3ccb93cd',
    messagingSenderId: '192172840760',
    projectId: 'test-7b9c2',
    storageBucket: 'test-7b9c2.appspot.com',
    iosBundleId: 'com.example.tugas1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAT06k0i_ZYYNgDY60bSXXwhgQGV6RhWc',
    appId: '1:192172840760:ios:ce8f2497993d1d3ccb93cd',
    messagingSenderId: '192172840760',
    projectId: 'test-7b9c2',
    storageBucket: 'test-7b9c2.appspot.com',
    iosBundleId: 'com.example.tugas1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDjCuLHvDk0Rg4VIBYNuROkY1s3pGVb4c',
    appId: '1:192172840760:web:dbac7b24714dd03acb93cd',
    messagingSenderId: '192172840760',
    projectId: 'test-7b9c2',
    authDomain: 'test-7b9c2.firebaseapp.com',
    storageBucket: 'test-7b9c2.appspot.com',
    measurementId: 'G-9FHBZQ9X6D',
  );
}
