name: tugas_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4

  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^17.2.4
  flutter_map: ^7.0.2
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: 4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  icon_forest: ^1.1.8
  image_cropper: ^1.5.1
  image_picker: ^0.8.5+3
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.3.2
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  webview_flutter: ^4.0.10
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
